apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodeapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodeapp
    app.kubernetes.io/part-of: test-application
  name: nodeapp
  namespace: karthik-jk
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nodeapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nodeapp
    spec:
      containers:
      - image: quay.io/karthik_jk/nodeapp@sha256:8324a5e569b83a71c1ea892210b15974b2f70a720fbc24bf1dc7a74aaebd68ef
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
